---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-capncrunch-com-logs
  namespace: web-system
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-a7541013.efs.us-east-1.amazonaws.com::fsap-0d2c00bf17c122d8b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-capncrunch-com-logs
  namespace: web-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-capncrunch-com
  namespace: web-system
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-a7541013.efs.us-east-1.amazonaws.com::fsap-00b3ef67fec1327c5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-capncrunch-com
  namespace: web-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi